---
resources:
- name: brain-aligned-delivery
  type: git
  source:
    uri: https://github.com/engineerbetter/brain-aligned-delivery.git

- name: kf-pipelines
  type: git
  source:
    uri: git@github.com:EngineerBetter/kf-pipelines.git
    private_key: ((git_private_key))
    branch: prod

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: brain-aligned-delivery
    trigger: true
  - set_pipeline: self
    file: brain-aligned-delivery/ci/pipeline.yml

- name: deploy-dev
  serial: true
  plan:
  - get: brain-aligned-delivery
    trigger: true
    passed: [set-pipeline]
  - get: kf-pipelines
  - task: kf-push
    file: kf-pipelines/ci/tasks/kf-push/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      manifest: brain-aligned-delivery
      source: brain-aligned-delivery
    params:
      MANIFEST: manifest-dev.yml
      GOOGLE_CREDENTIALS: ((ebkf-prod-app-developer-creds.gcp_credentials_json))
      REGION: ((ebkf-prod-app-developer-creds.region))
      CLUSTER: ((ebkf-prod-app-developer-creds.cluster_name))
      SPACE: development

- name: deploy-staging
  serial: true
  plan:
  - get: brain-aligned-delivery
    passed: [deploy-dev]
    trigger: true
  # - put: cf-staging
  #   params:
  #     path: brain-aligned-delivery
  #     manifest: brain-aligned-delivery/manifest-staging.yml

- name: deploy-prod
  serial: true
  plan:
  - get: brain-aligned-delivery
    passed: [deploy-staging]
    trigger: false
  # - put: cf-prod
  #   params:
  #     path: brain-aligned-delivery
  #     manifest: brain-aligned-delivery/manifest-prod.yml
